server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:/opt/app/api-gateway/gateway.p12
    key-store-password: changeit
    key-alias: gateway-ssl
  forward-headers-strategy: native

spring:
  application:
    name: api-gateway
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${EXTERNAL_ISSUER_URI:https://localhost:8443/realms/logistica}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://keycloak:8080/realms/logistica/protocol/openid-connect/certs}

logging:
  level:
    ar.edu.utn.frc.backend.logistica: INFO