services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
      KC_HOSTNAME_URL: "${PUBLIC_BASE_URL:-https://localhost:8443}"
    command: ["start-dev", "--import-realm"]
    networks: [ app-network ]
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro

  api-gateway:
    build:
      context: ./microservices/api-gateway
    environment:
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/logistica
      KEYCLOAK_JWK_URI: http://keycloak:8080/realms/logistica/protocol/openid-connect/certs
    ports:
      - "8443:8443"
    depends_on: [ keycloak ]
    networks: [ app-network ]

  ms-cliente:
    build: ./microservices/ms-cliente
    networks: [ app-network ]

  ms-transporte:
    build: ./microservices/ms-transporte
    networks: [ app-network ]

    

networks:
  app-network:
    driver: bridge
