server:
  port: 8080

spring:
  application:
    name: ms-transporte
  jpa:
    hibernate:
      ddl-auto: update

google:
  maps:
    api:
      url: https://tpi.wiremockapi.cloud
      key: falsa-api-key-para-pruebas

logging:
  level:
    ar.edu.utn.frc.backend.logistica: INFO
