server:
  port: 8082

spring:
  application:
    name: ms-transporte
  datasource:
    url: jdbc:h2:mem:mstransporte
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

# Google Maps API
google:
  maps:
    api:
      url: ${GOOGLE_MAPS_URL:https://maps.googleapis.com}
      key: ${GOOGLE_MAPS_API_KEY:fake-api-key-for-development}
